Update workflow

diff --git a/.github/workflows/build-push-docker-image.yml b/.github/workflows/build-push-docker-image.yml
--- a/.github/workflows/build-push-docker-image.yml
+++ b/.github/workflows/build-push-docker-image.yml
@@ -9,128 +9,127 @@ on:
     inputs:
       TARGET_ENV:
         type: choice
-        description: 'Please choose the Target environment'
-        default: 'test'
+        description: "Please choose the Target environment"
+        default: "test"
         required: true
         options:
-            - int
-            - test
-            - acc
-            - prod
+          - int
+          - test
+          - acc
+          - prod
 
       DEPLOYMENT_TYPE:
         type: choice
-        description: 'Please select the build only, deploy only or build and deploy'
-        default: 'build-and-deploy'
+        description: "Please select the build only, deploy only or build and deploy"
+        default: "build-and-deploy"
         required: true
         options:
-            - build
-            - deploy
-            - build-and-deploy
+          - build
+          - deploy
+          - build-and-deploy
 
 env:
-    IMAGE_REGISTRY: bwalia
-    TARGET_STACK: openresty_lua
-    IMAGE_NAME: opsapi
-    TARGET_IMAGE_TAG: latest
-    TARGET_ENV: ${{ github.event.inputs.TARGET_ENV || 'test' }}
-    DEPLOYMENT_TYPE: ${{ github.event.inputs.DEPLOYMENT_TYPE || 'build-and-deploy' }}
+  IMAGE_REGISTRY: bwalia
+  TARGET_STACK: openresty_lua
+  IMAGE_NAME: opsapi
+  TARGET_IMAGE_TAG: latest
+  TARGET_ENV: ${{ github.event.inputs.TARGET_ENV || 'test' }}
+  DEPLOYMENT_TYPE: ${{ github.event.inputs.DEPLOYMENT_TYPE || 'build-and-deploy' }}
 
 jobs:
   build:
-    runs-on: whisky03
+    runs-on: ubuntu-latest
 
     steps:
+      - name: Checkout code
+        if: ${{ env.DEPLOYMENT_TYPE == 'build' || env.DEPLOYMENT_TYPE == 'build-and-deploy' }}
+        uses: actions/checkout@v3
 
-    - name: Checkout code
-      if: ${{ env.DEPLOYMENT_TYPE == 'build' || env.DEPLOYMENT_TYPE == 'build-and-deploy' }}
-      uses: actions/checkout@v3
+      - name: Build OPSAPI Docker image based on the TARGET PLATFORM Image and push to Docker Hub
+        if: ${{ env.DEPLOYMENT_TYPE == 'build' || env.DEPLOYMENT_TYPE == 'build-and-deploy' }}
+        run: |
+          echo "OPSAPI Docker image builder!"
+          echo "Build, tag, and push image to the given Docker Registry."
+          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWD }}
+          docker build -f lapis/Dockerfile --build-arg TAG=latest -t test-${{ env.TARGET_STACK }} . --no-cache
+          docker tag test-${{ env.TARGET_STACK }} ${{ env.IMAGE_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.TARGET_IMAGE_TAG }}
+          docker push ${{ env.IMAGE_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.TARGET_IMAGE_TAG }}
+        shell: bash
 
-    - name: Build OPSAPI Docker image based on the TARGET PLATFORM Image and push to Docker Hub
-      if: ${{ env.DEPLOYMENT_TYPE == 'build' || env.DEPLOYMENT_TYPE == 'build-and-deploy' }}
-      run: |
-        echo "OPSAPI Docker image builder!"
-        echo "Build, tag, and push image to the given Docker Registry."
-        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWD }}
-        docker build -f lapis/Dockerfile --build-arg TAG=latest -t test-${{ env.TARGET_STACK }} . --no-cache
-        docker tag test-${{ env.TARGET_STACK }} ${{ env.IMAGE_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.TARGET_IMAGE_TAG }}
-        docker push ${{ env.IMAGE_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.TARGET_IMAGE_TAG }}
-      shell: bash        
+      # - name: Run Docker container
+      #   if: ${{ env.DEPLOYMENT_TYPE == 'build' || env.DEPLOYMENT_TYPE == 'build-and-deploy' }}
+      #   run: |
+      #         docker run -d -p 80:80 bwalia/opsapi:latest openresty -g "daemon off;"
 
-    # - name: Run Docker container
-    #   if: ${{ env.DEPLOYMENT_TYPE == 'build' || env.DEPLOYMENT_TYPE == 'build-and-deploy' }}
-    #   run: |
-    #         docker run -d -p 80:80 bwalia/opsapi:latest openresty -g "daemon off;"
+      # - name: Verify OpenResty is running
+      #   if: ${{ env.DEPLOYMENT_TYPE == 'build' || env.DEPLOYMENT_TYPE == 'build-and-deploy' }}
+      #   run: |
+      #         sleep 10 # Give some time for the server to start
+      #         curl -I http://localhost:80
 
-    # - name: Verify OpenResty is running
-    #   if: ${{ env.DEPLOYMENT_TYPE == 'build' || env.DEPLOYMENT_TYPE == 'build-and-deploy' }}
-    #   run: |
-    #         sleep 10 # Give some time for the server to start
-    #         curl -I http://localhost:80
-
-    - name: Slack Notification for OPSAPI release 
-      if: ${{ env.DEPLOYMENT_TYPE == 'build' || env.DEPLOYMENT_TYPE == 'build-and-deploy' }}
-      uses: rtCamp/action-slack-notify@v2
-      env:
-        SLACK_CHANNEL: general
-        SLACK_COLOR: ${{ job.status }}
-        SLACK_ICON: https://github.com/rtCamp.png?size=48
-        SLACK_MESSAGE: 'OPSAPI deployed to https://${{ env.TARGET_ENV }}.opsapi.io/ (${{ env.TARGET_ENV }}) env :rocket:'
-        SLACK_TITLE: OPSAPI deployment status
-        SLACK_USERNAME: rtCamp
-        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}            
+      - name: Slack Notification for OPSAPI release
+        if: ${{ env.DEPLOYMENT_TYPE == 'build' || env.DEPLOYMENT_TYPE == 'build-and-deploy' }}
+        uses: rtCamp/action-slack-notify@v2
+        env:
+          SLACK_CHANNEL: general
+          SLACK_COLOR: ${{ job.status }}
+          SLACK_ICON: https://github.com/rtCamp.png?size=48
+          SLACK_MESSAGE: "OPSAPI deployed to https://${{ env.TARGET_ENV }}.opsapi.io/ (${{ env.TARGET_ENV }}) env :rocket:"
+          SLACK_TITLE: OPSAPI deployment status
+          SLACK_USERNAME: rtCamp
+          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
 
   deploy:
-    runs-on: whisky03
-    needs: [ build ]
+    runs-on: ubuntu-latest
+    needs: [build]
     steps:
-    - name: Checkout code
-      uses: actions/checkout@v3
+      - name: Checkout code
+        uses: actions/checkout@v3
 
-    - name: Decode and Export Kubeconfig
-      if: ${{ env.DEPLOYMENT_TYPE == 'deploy' || env.DEPLOYMENT_TYPE == 'build-and-deploy' }}
-      env:
-        KUBECONFIG_BASE64: ${{ secrets.KUBE_CONFIG_DATA_K3S }}
-      run: |
-        echo "$KUBECONFIG_BASE64" | base64 -d > kubeconfig
-        export KUBECONFIG=$(pwd)/kubeconfig
-        echo "Kubeconfig decoded and exported successfully."
+      - name: Decode and Export Kubeconfig
+        if: ${{ env.DEPLOYMENT_TYPE == 'deploy' || env.DEPLOYMENT_TYPE == 'build-and-deploy' }}
+        env:
+          KUBECONFIG_BASE64: ${{ secrets.KUBE_CONFIG_DATA_K3S }}
+        run: |
+          echo "$KUBECONFIG_BASE64" | base64 -d > kubeconfig
+          export KUBECONFIG=$(pwd)/kubeconfig
+          echo "Kubeconfig decoded and exported successfully."
 
-    - name: Check and Install kubectl
-      if: ${{ env.DEPLOYMENT_TYPE == 'deploy' || env.DEPLOYMENT_TYPE == 'build-and-deploy' }}
-      run: |
-        if ! command -v kubectl &> /dev/null; then
-          echo "kubectl not found. Installing kubectl..."
-          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
-          chmod +x kubectl
-          sudo mv kubectl /usr/local/bin/
-        else
-          echo "kubectl is already installed."
-        fi
-      shell: bash
-  
-    - name: Check and Install Helm
-      if: ${{ env.DEPLOYMENT_TYPE == 'deploy' || env.DEPLOYMENT_TYPE == 'build-and-deploy' }}
-      run: |
-        if ! command -v helm &> /dev/null; then
-          echo "Helm not found. Installing Helm..."
-          curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
-        else
-          echo "Helm is already installed."
-        fi
-      shell: bash
+      - name: Check and Install kubectl
+        if: ${{ env.DEPLOYMENT_TYPE == 'deploy' || env.DEPLOYMENT_TYPE == 'build-and-deploy' }}
+        run: |
+          if ! command -v kubectl &> /dev/null; then
+            echo "kubectl not found. Installing kubectl..."
+            curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
+            chmod +x kubectl
+            sudo mv kubectl /usr/local/bin/
+          else
+            echo "kubectl is already installed."
+          fi
+        shell: bash
 
-    - name: Deploy Helm Chart
-      if: ${{ env.DEPLOYMENT_TYPE == 'deploy' || env.DEPLOYMENT_TYPE == 'build-and-deploy' }}
-      run: |
-        export KUBECONFIG=$(pwd)/kubeconfig
-        echo "Deploying Helm chart for ${{ env.TARGET_ENV }} environment..."
-        kubectl config use-context ${{ env.TARGET_ENV }}-k3s
-        echo "Helm deleting existing release if it exists..."
-        helm delete ${{ env.IMAGE_NAME }} --namespace ${{ env.TARGET_ENV }} || true
-        echo "Helm upgrading or installing the release..."
-        helm upgrade --install ${{ env.IMAGE_NAME }} ./devops/helm-chart \
-          -f ./devops/helm-chart/values-${{ env.TARGET_ENV }}.yaml \
-          --set image.repository=bwalia/opsapi \
-          --set image.tag=latest \
-          --namespace ${{ env.TARGET_ENV }} --create-namespace
+      - name: Check and Install Helm
+        if: ${{ env.DEPLOYMENT_TYPE == 'deploy' || env.DEPLOYMENT_TYPE == 'build-and-deploy' }}
+        run: |
+          if ! command -v helm &> /dev/null; then
+            echo "Helm not found. Installing Helm..."
+            curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
+          else
+            echo "Helm is already installed."
+          fi
+        shell: bash
+
+      - name: Deploy Helm Chart
+        if: ${{ env.DEPLOYMENT_TYPE == 'deploy' || env.DEPLOYMENT_TYPE == 'build-and-deploy' }}
+        run: |
+          export KUBECONFIG=$(pwd)/kubeconfig
+          echo "Deploying Helm chart for ${{ env.TARGET_ENV }} environment..."
+          kubectl config use-context ${{ env.TARGET_ENV }}-k3s
+          echo "Helm deleting existing release if it exists..."
+          helm delete ${{ env.IMAGE_NAME }} --namespace ${{ env.TARGET_ENV }} || true
+          echo "Helm upgrading or installing the release..."
+          helm upgrade --install ${{ env.IMAGE_NAME }} ./devops/helm-chart \
+            -f ./devops/helm-chart/values-${{ env.TARGET_ENV }}.yaml \
+            --set image.repository=bwalia/opsapi \
+            --set image.tag=latest \
+            --namespace ${{ env.TARGET_ENV }} --create-namespace
