Update deployment

diff --git a/.github/workflows/build-push-docker-image.yml b/.github/workflows/build-push-docker-image.yml
--- a/.github/workflows/build-push-docker-image.yml
+++ b/.github/workflows/build-push-docker-image.yml
@@ -10,7 +10,7 @@ on:
       TARGET_ENV:
         type: choice
         description: 'Please choose the Target environment'
-        default: 'int'
+        default: 'test'
         required: true
         options:
             - int
@@ -18,23 +18,36 @@ on:
             - acc
             - prod
 
+      DEPLOYMENT_TYPE:
+        type: choice
+        description: 'Please select the build only, deploy only or build and deploy'
+        default: 'build-and-deploy'
+        required: true
+        options:
+            - build
+            - deploy
+            - build-and-deploy
+
 env:
     IMAGE_REGISTRY: bwalia
     TARGET_STACK: openresty_lua
     IMAGE_NAME: opsapi
     TARGET_IMAGE_TAG: latest
-    TARGET_ENV: ${{ github.event.inputs.TARGET_ENV || 'int' }}
+    TARGET_ENV: ${{ github.event.inputs.TARGET_ENV || 'test' }}
+    DEPLOYMENT_TYPE: ${{ github.event.inputs.DEPLOYMENT_TYPE || 'build-and-deploy' }}
 
 jobs:
   build:
-    runs-on: ubuntu-latest
+    runs-on: whisky03
 
     steps:
 
     - name: Checkout code
+      if: ${{ env.DEPLOYMENT_TYPE == 'build' || env.DEPLOYMENT_TYPE == 'build-and-deploy' }}
       uses: actions/checkout@v3
 
     - name: Build OPSAPI Docker image based on the TARGET PLATFORM Image and push to Docker Hub
+      if: ${{ env.DEPLOYMENT_TYPE == 'build' || env.DEPLOYMENT_TYPE == 'build-and-deploy' }}
       run: |
         echo "OPSAPI Docker image builder!"
         echo "Build, tag, and push image to the given Docker Registry."
@@ -45,15 +58,18 @@ jobs:
       shell: bash        
 
     - name: Run Docker container
+      if: ${{ env.DEPLOYMENT_TYPE == 'build' || env.DEPLOYMENT_TYPE == 'build-and-deploy' }}
       run: |
             docker run -d -p 80:80 bwalia/opsapi:latest openresty -g "daemon off;"
 
     - name: Verify OpenResty is running
+      if: ${{ env.DEPLOYMENT_TYPE == 'build' || env.DEPLOYMENT_TYPE == 'build-and-deploy' }}
       run: |
             sleep 10 # Give some time for the server to start
             curl -I http://localhost:80
 
     - name: Slack Notification for OPSAPI release 
+      if: ${{ env.DEPLOYMENT_TYPE == 'build' || env.DEPLOYMENT_TYPE == 'build-and-deploy' }}
       uses: rtCamp/action-slack-notify@v2
       env:
         SLACK_CHANNEL: general
@@ -63,3 +79,52 @@ jobs:
         SLACK_TITLE: OPSAPI deployment status
         SLACK_USERNAME: rtCamp
         SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}            
+
+  deploy:
+    runs-on: whisky03
+
+    steps:
+    - name: Checkout code
+      uses: actions/checkout@v3
+
+    - name: Decode and Export Kubeconfig
+      if: ${{ env.DEPLOYMENT_TYPE == 'deploy' || env.DEPLOYMENT_TYPE == 'build-and-deploy' }}
+      env:
+        KUBECONFIG_BASE64: ${{ secrets.KUBE_CONFIG_DATA_K3S }}
+      run: |
+        echo "$KUBECONFIG_BASE64" | base64 -d > kubeconfig
+        export KUBECONFIG=$(pwd)/kubeconfig
+        echo "Kubeconfig decoded and exported successfully."
+
+    - name: Check and Install kubectl
+      if: ${{ env.DEPLOYMENT_TYPE == 'deploy' || env.DEPLOYMENT_TYPE == 'build-and-deploy' }}
+      run: |
+        if ! command -v kubectl &> /dev/null; then
+          echo "kubectl not found. Installing kubectl..."
+          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
+          chmod +x kubectl
+          sudo mv kubectl /usr/local/bin/
+        else
+          echo "kubectl is already installed."
+        fi
+      shell: bash
+  
+    - name: Check and Install Helm
+      if: ${{ env.DEPLOYMENT_TYPE == 'deploy' || env.DEPLOYMENT_TYPE == 'build-and-deploy' }}
+      run: |
+        if ! command -v helm &> /dev/null; then
+          echo "Helm not found. Installing Helm..."
+          curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
+        else
+          echo "Helm is already installed."
+        fi
+      shell: bash
+
+    - name: Deploy Helm Chart
+      if: ${{ env.DEPLOYMENT_TYPE == 'deploy' || env.DEPLOYMENT_TYPE == 'build-and-deploy' }}
+      run: |
+        export KUBECONFIG=$(pwd)/kubeconfig
+        helm upgrade --install ${{ env.IMAGE_NAME }} ./devops/helm-chart \
+          --set image.repository=bwalia/opsapi \
+          --set image.tag=latest \
+          --namespace ${{ env.TARGET_ENV }} --create-namespace
